app:
  baseUrl: https://glorious-fishstick-q965vvj6jg934j9w-7007.app.github.dev/
backend:
  auth:
    keys:
    - secret: FSzgMhrle7mDK68wTLHD5fVc
  baseUrl: https://glorious-fishstick-q965vvj6jg934j9w-7007.app.github.dev/
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    img-src:
      - "'self'"
      - 'data:'
  cors:
    origin: https://glorious-fishstick-q965vvj6jg934j9w-7007.app.github.dev/
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true  
  database:
    connection:
      password: rhdh
      user: rhdhadmin
      host: postgres
dynamicPlugins:
  rootDirectory: dynamic-plugins-root